/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "IDRSyNAA8gXR80d6Htl3HWg",
        engine: "postgresql",
        connectionUri: secret("SQL_CONNECTION_STRING"),
        vpcConfig: {
            vpcId: "vpc-0b78a102d41b48bac",
            securityGroupIds: [
                "sg-08648ca7984eb3c43"
            ],
            subnetAvailabilityZones: [
                {
                    subnetId: "subnet-07633f198fb02cf82",
                    availabilityZone: "ap-northeast-1d"
                },
                {
                    subnetId: "subnet-0fa3a5580f5138c54",
                    availabilityZone: "ap-northeast-1c"
                },
                {
                    subnetId: "subnet-04b5c6fc9630ccfdc",
                    availabilityZone: "ap-northeast-1a"
                }
            ]
        }
    }
}).schema({
    "events": a.model({
        id: a.integer().required(),
        name: a.string(),
        geom: a.string()
    }).identifier([
        "id"
    ]),
    "notes": a.model({
        id: a.id().required(),
        content: a.string(),
        owner: a.string()
    }).identifier([
        "id"
    ]),
    "spatial_ref_sys": a.model({
        srid: a.integer().required(),
        auth_name: a.string(),
        auth_srid: a.integer(),
        srtext: a.string(),
        proj4text: a.string()
    }).identifier([
        "srid"
    ]),
    "users": a.model({
        id: a.string().required(),
        name: a.string().required(),
        email: a.string().required()
    }).identifier([
        "id"
    ])
});
